---
abstract: 'PerlFormance - Invariant cargo files'
author:
  - 'Steffen Schwigon, C<< <ss5 at renormalist.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Perl-Formance-Cargo
no_index:
  directory:
    - inc
    - t
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Benchmark-Perl-Formance-Cargo
  license: http://dev.perl.org/licenses/
  repository: git://github.com/renormalist/Benchmark-Perl-Formance-Cargo.git
version: 0.03
